server:
  port: 8181

spring:
  main:
    banner-mode: off
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

floodlight:
  prioritization:
    enabled: false
    meter-switch: 00:00:00:00:00:00:00:06
    queue-switch: 00:00:00:00:00:00:00:07
    flows:
      "10.0.0.1": "10.0.0.5"
      "10.0.0.2": "10.0.0.5"
  topology-uri: http://localhost:8080/qos/switches/topology
  switches-uri: http://localhost:8080/qos/switches/json
  flows-uri: http://localhost:8080/qos/flows/json
